apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-web-app-ingress
  namespace: cert-manager
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
  - host: groveops.net
    http:
      paths:
      - path: //usr/share/nginx/html/favicon.ico
        pathType: Prefix
        backend:
          service:
            name: simple-web-app-service
            port:
              number: 80
  tls:
  - hosts:
    - groveops.net
    - "*.groveops.net"
    secretName: example-com-tls