apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-binding
subjects:
  - kind: ServiceAccount
    name: cert-manager-sa
    namespace: cert-manager
roleRef:
  kind: ClusterRole
  name: cert-manager
  apiGroup: rbac.authorization.k8s.io